
name: Deploy Alumni-Project

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:

jobs:
  # Test both server and client
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Backend (Server) Testing
      - name: Set up Node.js for backend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install backend dependencies
        working-directory: ./'UI Admin'/server
        run: npm install


      # Frontend (Client) Testing
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./'UI User'/client
        run: npm install


  # Build and push Docker images for both backend and frontend
  Build:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


      # Build and push backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t abdelaali2550/alumni-backend:latest ./'UI Admin'/server

      - name: Push backend Docker image
        run: docker push abdelaali2550/alumni-backend:latest

      # Build and push frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker build -t abdelaali2550/alumni-frontenddd:latest ./'UI User'/client

      - name: Push frontend Docker image
        run: docker push abdelaali2550/alumni-frontenddd:latest


  # Deploy both backend and frontend
  Deploy:
    needs: Build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy backend
      - name: Pull and run backend container
        run: |
           docker pull abdelaali2550/alumni-backend:latest
           docker stop alumni-backend-container || true
           docker rm alumni-backend-container || true
           docker run -d -p 3001:3001 --name alumni-backend-container \
          -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
          abdelaali2550/alumni-backend:latest


      # Deploy frontend
      - name: Pull and run frontend container
        run: |
          docker pull abdelaali2550/alumni-frontenddd:latest
          docker stop alumni-frontenddd-container || true
          docker rm alumni-frontenddd-container || true
          docker run -d -p 5173:80 --name alumni-frontenddd-container \
          abdelaali2550/alumni-frontenddd:latest
